language: python
python:
- '2.7'
install: make deps
script: make all
deploy:
  provider: s3
  access_key_id: AKIAJUOL2JDEXSEYFEPQ
  secret_access_key:
    secure: bAJNJUBgNUo9O5dWAgmumO67v3esn7lnikaZHHbD98PLuRHjuL3snKYpl2Yxvpvrtl1dpDUpf6hKnXdagy3DJjtkcbUXohRKnahdV6RD8oUy0UJSvS/7FiHpjVYkprUxYwnSo8mDFWSSW7Ebn0hhw4ntnm3ov8Bj0VQwyRdV5Q8=
  bucket: vocab-ld.org
  local-dir: src
  acl: public_read
  on:
    repo: ericmoritz/vocab-ld.org
