language: python
python:
- '2.7'
install: make deps
script: make all
deploy:
  provider: s3
  access_key_id: AKIAJ6LYU74WC2KXL4UA
  secret_access_key:
    secure: JrBiuoB8Hgmg72QXB0KLSUiB14Dcip5iJX5GR6OW6ORLHCy24cUhnGBsoGNexvq8TWHPDbLxaxRiQvv5YtsvdknEXpSqdn380iLM+7HrJS7X4ePA4yWTvbnW+7CIZkmeJtp2eyvg9gUD4mKOYB/SYSteItEasVGPMDrGJCE2HZ0=
  bucket: rdf.vocab-ld.org
  acl: public_read
  on:
    repo: ericmoritz/vocab-ld.org
